[package]
name = "libffi"
version = "0.1.11"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
build = "build.rs"
description = "Rust bindings for libffi"
repository = "https://github.com/tov/libffi-rs"
homepage = "https://github.com/tov/libffi-rs"
documentation = "http://tov.github.io/libffi-rs/"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["ffi", "libffi", "closure", "c"]

[features]
unique = []

[dependencies]
abort_on_panic = "1.0.0"
libc = "0.2.11"
clippy = { version = "0", optional = true }

[build-dependencies]
pkg-config = "0.3.7"
bindgen = "0.18"
