[package]
name = "libffi"
version = "0.1.0"
authors = ["Jesse A. Tov <jesse.tov@gmail.com>"]
build = "build.rs"
description = "Rust bindings for libffi"
repository = "https://github.com/tov/libffi-rs"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.2.11"

[build-dependencies]
pkg-config = "0.3.7"
